package com.ramy.bugreport.persistence.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import com.ramy.bugreport.domain.EBugSeverity;
import com.ramy.bugreport.domain.EBugStatus;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code bug_report} table; persistence counterpart of {@link com.ramy.bugreport.domain.BugReport}.
 *
 * Reporter, assignee, project and component are stored as plain UUID columns rather than JPA
 * relationships (the foreign keys exist only in the SQL migration). The only mapped relationship
 * is {@link #resolution}.
 */
@Entity
@Table(name = "bug_report")
public class BugReportEntity {

    /** Primary key, generated by JPA as a UUID and stored as CHAR(36). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", nullable = false, length = 36)
    private UUID id;

    /** Id of the reporting user ({@code user_account}). Not null. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "reporter_id", nullable = false, length = 36)
    private UUID reporterId;

    /** Id of the assigned user ({@code user_account}). Null while unassigned. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "assignee_id", length = 36)
    private UUID assigneeId;

    /** Id of the {@code software_project}. Not null. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "project_id", nullable = false, length = 36)
    private UUID projectId;

    /** Id of the {@code component}. Null if the report has no component. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "component_id", length = 36)
    private UUID componentId;

    /** Short summary. Not null, up to 255 characters. */
    @Column(name = "title", nullable = false)
    private String title;

    /** Free-text description, TEXT column. Nullable. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** Steps to reproduce, TEXT column. Nullable. */
    @Column(name = "steps_to_reproduce", columnDefinition = "TEXT")
    private String stepsToReproduce;

    /** Expected behavior, TEXT column. Nullable. */
    @Column(name = "expected_behavior", columnDefinition = "TEXT")
    private String expectedBehavior;

    /** Actual behavior, TEXT column. Nullable. */
    @Column(name = "actual_behavior", columnDefinition = "TEXT")
    private String actualBehavior;

    /** Severity, stored as the enum name (VARCHAR). Not null; a database CHECK restricts allowed values. */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "severity", nullable = false, length = 32)
    private EBugSeverity severity;

    /** Workflow status, stored as the enum name (VARCHAR). Not null; a database CHECK restricts allowed values. */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "status", nullable = false, length = 32)
    private EBugStatus status;

    /** Creation time. Not null. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** Last modification time. Not null. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Resolution of this report, or null while unresolved.
     *
     * One-to-one, loaded lazily. Saving or deleting the report cascades to the resolution, and a
     * resolution that is detached from the report is deleted (orphan removal). The {@code resolution_id}
     * column is unique, so a resolution belongs to at most one report.
     */
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "resolution_id", unique = true)
    private ResolutionEntity resolution;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getReporterId() {
        return reporterId;
    }

    public void setReporterId(UUID reporterId) {
        this.reporterId = reporterId;
    }

    public UUID getAssigneeId() {
        return assigneeId;
    }

    public void setAssigneeId(UUID assigneeId) {
        this.assigneeId = assigneeId;
    }

    public UUID getProjectId() {
        return projectId;
    }

    public void setProjectId(UUID projectId) {
        this.projectId = projectId;
    }

    public UUID getComponentId() {
        return componentId;
    }

    public void setComponentId(UUID componentId) {
        this.componentId = componentId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStepsToReproduce() {
        return stepsToReproduce;
    }

    public void setStepsToReproduce(String stepsToReproduce) {
        this.stepsToReproduce = stepsToReproduce;
    }

    public String getExpectedBehavior() {
        return expectedBehavior;
    }

    public void setExpectedBehavior(String expectedBehavior) {
        this.expectedBehavior = expectedBehavior;
    }

    public String getActualBehavior() {
        return actualBehavior;
    }

    public void setActualBehavior(String actualBehavior) {
        this.actualBehavior = actualBehavior;
    }

    public EBugSeverity getSeverity() {
        return severity;
    }

    public void setSeverity(EBugSeverity severity) {
        this.severity = severity;
    }

    public EBugStatus getStatus() {
        return status;
    }

    public void setStatus(EBugStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public ResolutionEntity getResolution() {
        return resolution;
    }

    public void setResolution(ResolutionEntity resolution) {
        this.resolution = resolution;
    }
}
