package com.ramy.bugreport.persistence.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code comment} table; persistence counterpart of {@link com.ramy.bugreport.domain.Comment}.
 * The bug report and author are stored as plain UUID columns.
 */
@Entity
@Table(name = "comment")
public class CommentEntity {

    /** Primary key, generated by JPA as a UUID and stored as CHAR(36). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", nullable = false, length = 36)
    private UUID id;

    /** Id of the commented {@code bug_report}. Not null. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "bug_report_id", nullable = false, length = 36)
    private UUID bugReportId;

    /** Id of the author ({@code user_account}). Not null. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "author_id", nullable = false, length = 36)
    private UUID authorId;

    /** Comment text, TEXT column. Not null. */
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    /** When the comment was written. Not null. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getBugReportId() {
        return bugReportId;
    }

    public void setBugReportId(UUID bugReportId) {
        this.bugReportId = bugReportId;
    }

    public UUID getAuthorId() {
        return authorId;
    }

    public void setAuthorId(UUID authorId) {
        this.authorId = authorId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
