package com.ramy.bugreport.persistence.entity;

import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code component} table; persistence counterpart of {@link com.ramy.bugreport.domain.Component}.
 * The responsible user is stored as a plain UUID column.
 */
@Entity
@Table(name = "component")
public class ComponentEntity {

    /** Primary key, generated by JPA as a UUID and stored as CHAR(36). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", nullable = false, length = 36)
    private UUID id;

    /** Display name. Not null, up to 255 characters. */
    @Column(name = "name", nullable = false)
    private String name;

    /** Free-text description, TEXT column. Nullable. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** Id of the responsible user ({@code user_account}). Not null. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "responsible_user_id", nullable = false, length = 36)
    private UUID responsibleUserId;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public UUID getResponsibleUserId() {
        return responsibleUserId;
    }

    public void setResponsibleUserId(UUID responsibleUserId) {
        this.responsibleUserId = responsibleUserId;
    }
}
