package com.ramy.bugreport.persistence.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code resolution} table; persistence counterpart of {@link com.ramy.bugreport.domain.Resolution}.
 * Owned by {@link BugReportEntity#getResolution()}, which cascades saves and deletes to it.
 */
@Entity
@Table(name = "resolution")
public class ResolutionEntity {

    /** Primary key, generated by JPA as a UUID and stored as CHAR(36). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", nullable = false, length = 36)
    private UUID id;

    /** What was done to fix the bug, TEXT column. Nullable. */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /** When the bug was resolved. Not null. */
    @Column(name = "resolved_at", nullable = false)
    private LocalDateTime resolvedAt;

    /** Version containing the fix, up to 100 characters. Nullable. */
    @Column(name = "fixed_version", length = 100)
    private String fixedVersion;

    /** URL of the fixing commit, up to 2048 characters. Nullable. */
    @Column(name = "commit_url", length = 2048)
    private String commitUrl;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    public String getFixedVersion() {
        return fixedVersion;
    }

    public void setFixedVersion(String fixedVersion) {
        this.fixedVersion = fixedVersion;
    }

    public String getCommitUrl() {
        return commitUrl;
    }

    public void setCommitUrl(String commitUrl) {
        this.commitUrl = commitUrl;
    }
}
