package com.ramy.bugreport.persistence.entity;

import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import com.ramy.bugreport.domain.EUserRole;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/** JPA entity for the {@code user_account} table; persistence counterpart of {@link com.ramy.bugreport.domain.UserAccount}. */
@Entity
@Table(name = "user_account")
public class UserAccountEntity {

    /** Primary key, generated by JPA as a UUID and stored as CHAR(36). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", nullable = false, length = 36)
    private UUID id;

    /** Display name. Not null, up to 255 characters. */
    @Column(name = "name", nullable = false)
    private String name;

    /** Email address. Not null and unique (database constraint). */
    @Column(name = "email_address", nullable = false, length = 255, unique = true)
    private String emailAddress;

    /** BCrypt password hash, never the plain password. Not null. */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /** Role, stored as the enum name (VARCHAR). Not null; a database CHECK restricts allowed values. */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "role", nullable = false, length = 32)
    private EUserRole role;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public EUserRole getRole() {
        return role;
    }

    public void setRole(EUserRole role) {
        this.role = role;
    }
}
